project:
  uuid: 0770eb51-49be-4f20-8f4f-0edcf54ae292
  slug: nichthub
  node_id: 752e6076aa27
  build_id: ece07f81-5366-5cb0-a0cf-25581682c2b9
mission_type_activations:
- software-dev
- documentation
- research
- plan
vcs:
  type: git
agents:
  available:
  - codex
  auto_commit: true
  lint_on_edit: false
